### ISSUE TITLE
KeyError 'language_prefix'

### ISSUE THREAD

**Issue by kevinvalk** [facelessuser/sublime-pymdownx#2]
Hi, not completely sure what happened, but my Sublime Text 3 has trouble with this package.

```
mdpopups: Failed to load markdown module!
Traceback (most recent call last):
  File "C:\...\Sublime Text 3\Data\Installed Packages\LSP.sublime-package\plugin/hover.py", line 207, in <lambda>
  File "C:\...\Sublime Text 3\Data\Installed Packages\LSP.sublime-package\plugin/hover.py", line 210, in show_hover
  File "C:\...\Sublime Text 3\Data\Installed Packages\LSP.sublime-package\plugin/hover.py", line 202, in hover_content
  File "C:\...\Sublime Text 3\Data\Packages\mdpopups\st3\mdpopups\__init__.py", line 441, in md2html
    ).convert(_markup_template(markup, template_vars, template_env_options)).replace('&quot;', '"')
  File "C:\...\Sublime Text 3\Data\Packages\PYTHON~1\st3\markdown\core.py", line 268, in convert
    newRoot = treeprocessor.run(root)
  File "C:\...\Sublime Text 3\Data\Packages\PYTHON~1\st3\markdown\treeprocessors.py", line 371, in run
    self.__handleInline(text), child
  File "C:\...\Sublime Text 3\Data\Packages\PYTHON~1\st3\markdown\treeprocessors.py", line 132, in __handleInline
    self.inlinePatterns[patternIndex], data, patternIndex, startIndex
  File "C:\...\Sublime Text 3\Data\Packages\PYTHON~1\st3\markdown\treeprocessors.py", line 272, in __applyPattern
    node, start, end = pattern.handleMatch(match, data)
  File "C:\...\Sublime Text 3\Data\Packages\pymdownx\st3\pymdownx\inlinehilite.py", line 173, in handleMatch
    self.get_settings()
  File "C:\...\Sublime Text 3\Data\Packages\pymdownx\st3\pymdownx\inlinehilite.py", line 129, in get_settings
    self.language_prefix = config['language_prefix']
```

Which has indeed been recently introduced: https://github.com/facelessuser/sublime-pymdownx/commit/0eed7cfcb43fe39b20a6be693adaa3ef03b0231e#diff-1fcf67a893b0bb36e9a4a5510292cf97792db2390a1e08562ee701f123a7b0f9R129

I am using some markdown plugins:
- MarkdownEditing v.2.2.9
- MarkdownPreview v2.3.0
- MarkdownTOC v4.1.2

Sublime Text version 3.2.2 (Build 3211)

Please let me know if you need more information.

**Comment by facelessuser** [comment]
Run `Package Control: Satisfy Dependencies`. PC does a not so great job of updating dependencies. Make sure to restart Sublime.

**Comment by kevinvalk** [comment]
Perfect, that was indeed the solution!
```
Package Control: The dependency 'mdpopups' is installed, but out of date; upgrading to latest release 4.0.0 from 3.7.5...
reloading settings Packages/mdpopups/Preferences.sublime-settings
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: All dependencies have been satisfied
```

Thanks for the super quick response 🥇
